#!/bin/sh
echo "install git and mercurial"
apk add --update git mercurial

echo "install godep"
go get github.com/tools/godep

echo "build mesos-dns"
cd /go/src/github.com/mesosphere/mesos-dns
git checkout v0.5.1
sed -i 's/"dev"/"0.5.1"/g' version.go
godep go install 
